### PR TITLE
Fixed the issue: was storing the timestamps as strings, not Date obje…

### LINKED ISSUE #18: Can't correctly sort by Date/time

### PR DESCRIPTION
**Pull request by OmicronPersei**
Closes #18

### CODE REVIEW

File: node_server/rest_endpoints.js [hunk 1]
```diff
@@ -45,9 +45,11 @@ const sortShots = function(sortOrder, sortedColId, shots) {
         
         if (matchingCol.sortAsNumber) {
             if (isAsc) {
-                return aVal - bVal;
+                let diff = aVal - bVal
+                return diff;
```
Comment (OmicronPersei) [inline node_server/rest_endpoints.js]: Is instrumentation code for debugging, revert.
